-- ============================================================================
-- Vietnam Trip — initial Supabase schema, security and storage setup
-- ============================================================================
--
-- WHAT THIS IS
-- This is documentation/setup SQL. Paste the whole file into the Supabase
-- SQL Editor and run it manually. Nothing in this repository executes it —
-- the running app does NOT connect to Supabase yet (that is a later step).
--
-- WHAT THIS DOES NOT DO
-- It does not move or copy any existing trip data. It only creates empty
-- tables, security policies, an image storage bucket, and Realtime wiring.
-- Migrating the current itinerary-backup.json content into these tables is
-- a separate, later step.
--
-- SOURCE OF TRUTH
-- Column names/shapes are taken directly from the app's current in-memory
-- model (post "Phase 0" refactor), specifically:
--   src/components/Itinerary.js   (stops: loc, date, desc, cost, photo,
--                                   journey, activities, accommodations,
--                                   accommodationWishlistUrl,
--                                   selectedAccommodationId)
--   src/components/Journey.js     (journey legs/stopovers — makeLeg/makeStopover)
--   src/components/ActivityGrid.js/ActivityCard.js/ActivityFields.js (activities)
--   src/components/AccommodationSection.js/AccommodationCard.js (accommodations)
--   src/lib/travellers.js         (traveller shape)
--   src/components/TripPlanner.js (depart/return/extraCosts)
--   src/components/CostSummary.js (extraCosts shape)
--
-- WHAT IS DELIBERATELY *NOT* CREATED HERE (derived UI state — stays client-side)
--   - MAP pins/routes/selection (derived from stops + the static
--     src/lib/mapCoordinates.js lookup table)
--   - VOTES dashboard groupings ("Everyone's picks" / "Contenders" / etc.)
--   - Cost Summary totals
--   - active navigation tab, MAP's selected destination
-- All of these are recomputed live from the tables below, exactly as the
-- app already does from its in-memory `stops` state.
--
-- SECURITY MODEL (revised after review)
-- The app will sign every site visitor in via Supabase anonymous auth
-- automatically. That alone gives them Postgres role `authenticated` — the
-- same role a real family member's session has — so a policy of "allow any
-- authenticated request" would really mean "allow anyone who finds the
-- public GitHub Pages URL". That is NOT an acceptable boundary for a
-- private trip, so it is not what this file does.
--
-- Instead, every table's access is gated on genuine trip MEMBERSHIP
-- (public.trip_access), which a visitor only gets by successfully calling
-- public.join_trip() with the trip's one shared invite code/passphrase —
-- see section 3 for the full mechanism and rationale. `authenticated` is
-- necessary but no longer sufficient anywhere in this file.
--
-- STABLE IDS
-- Every table uses a uuid primary key generated by the database
-- (gen_random_uuid()). Once a row is created, that id never changes — which
-- is exactly what "stable id" means for this app's reorder, MAP deep-link,
-- duplicate-Hanoi-stop, vote and accommodation-selection logic. (The current
-- app's short string ids like "idp0mix79k4zn8" are a JSON-seed artifact —
-- the later migration step will map each of those to a newly generated uuid
-- once, and from then on that uuid is permanent.)
--
-- RE-RUNNING THIS FILE
-- Written to be safe to run more than once: tables/indexes use
-- IF NOT EXISTS, and policies/triggers/publication entries are dropped and
-- re-created rather than erroring if they already exist. Re-running it will
-- NOT drop or change any data you've already put in these tables. It is
-- meant for the initial setup only — once the app is live, future schema
-- changes should be their own small additive SQL files, not edits to this
-- one (see the audit's "schema evolution" guidance).
--
-- ============================================================================


-- ----------------------------------------------------------------------------
-- 0. Extensions
-- ----------------------------------------------------------------------------
-- gen_random_uuid() — used as the default for every primary key below.
create extension if not exists pgcrypto;


-- ----------------------------------------------------------------------------
-- 1. Tables
-- ----------------------------------------------------------------------------
-- Created in dependency order. `stops` and `accommodations` reference each
-- other (a stop's selected stay is one of its own accommodation rows), so
-- `stops.selected_accommodation_id` is added as a plain column here and its
-- foreign key is attached afterwards with ALTER TABLE, once `accommodations`
-- exists — this avoids any circular create-order problem.

-- --- trips -------------------------------------------------------------
-- One row per trip. Only one row is expected to exist for now (this app has
-- no trip-switcher UI), but modelling it as its own table keeps every other
-- table cleanly scoped via trip_id, and leaves room for more trips later.
create table if not exists public.trips (
  id               uuid primary key default gen_random_uuid(),
  title            text,
  subtitle         text,
  depart           date,
  return_date      date,
  currency         text not null default '£',
  hero_photo_url   text,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);
comment on table public.trips is 'One row per trip. title/subtitle/hero photo are not yet editable in the app, but are modelled here so the full trip is represented.';

-- --- trip_invite_codes -----------------------------------------------------
-- The one shared "family passphrase" for this trip. Stored hashed
-- (pgcrypto's crypt()/gen_salt('bf')) so the plaintext code never sits in
-- the database at rest — only public.join_trip() below can check it, and
-- ordinary API access (anon or authenticated) is refused entirely (see the
-- RLS section: this table gets RLS enabled with NO policies for those
-- roles, so it isn't readable via the API at all, only via the function).
create table if not exists public.trip_invite_codes (
  trip_id     uuid primary key references public.trips(id) on delete cascade,
  code_hash   text not null,
  created_at  timestamptz not null default now()
);
comment on table public.trip_invite_codes is 'One shared invite code per trip, hashed. Never exposed directly via the API — only checked inside public.join_trip().';

-- --- trip_access -------------------------------------------------------
-- Real trip membership. This is the actual authorization boundary — every
-- other table's RLS policy checks THIS table (via is_trip_member below),
-- not merely "is this request authenticated". A row only ever appears here
-- via public.join_trip() succeeding; there is no direct-insert policy for
-- ordinary users.
create table if not exists public.trip_access (
  trip_id     uuid not null references public.trips(id) on delete cascade,
  user_id     uuid not null references auth.users(id) on delete cascade,
  joined_at   timestamptz not null default now(),
  primary key (trip_id, user_id)
);
comment on table public.trip_access is 'Trip membership: one row per (trip, Supabase auth user) that has successfully called join_trip() with the correct invite code. This table — not "authenticated" alone — is the real access boundary.';

-- --- travellers ----------------------------------------------------------
create table if not exists public.travellers (
  id           uuid primary key default gen_random_uuid(),
  trip_id      uuid not null references public.trips(id) on delete cascade,
  name         text not null default '',
  initials     text not null default '',
  included     boolean not null default true,
  voter        boolean not null default false,
  sort_order   integer not null default 0,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);
comment on table public.travellers is 'The trip party. voter = eligible to vote on activities/accommodation. included = currently part of the headcount/cost split.';

-- --- stops (destinations) -------------------------------------------------
-- selected_accommodation_id intentionally has NO inline foreign key yet —
-- see the ALTER TABLE after `accommodations` is created below.
create table if not exists public.stops (
  id                          uuid primary key default gen_random_uuid(),
  trip_id                     uuid not null references public.trips(id) on delete cascade,
  loc                         text not null default '',
  date                        date,
  description                 text not null default '',
  cost                        numeric(10,2) not null default 0 check (cost >= 0),
  photo_url                   text,
  accommodation_wishlist_url  text,
  selected_accommodation_id   uuid,
  sort_order                  integer not null default 0,
  created_at                  timestamptz not null default now(),
  updated_at                  timestamptz not null default now(),
  updated_by                  uuid references public.travellers(id) on delete set null
);
comment on table public.stops is 'One row per destination/stop, e.g. Hanoi, Sapa, Hanoi (return). `loc` is the destination name. Order is sort_order, not row-insertion order — the app reorders these freely, including two stops that share the same destination name.';

-- --- accommodations --------------------------------------------------------
create table if not exists public.accommodations (
  id               uuid primary key default gen_random_uuid(),
  stop_id          uuid not null references public.stops(id) on delete cascade,
  name             text not null default '',
  type             text not null default '',
  location         text not null default '',
  image_url        text,
  price_per_night  numeric(10,2) check (price_per_night is null or price_per_night >= 0),
  total_price      numeric(10,2) check (total_price is null or total_price >= 0),
  rating           numeric(2,1) check (rating is null or (rating >= 0 and rating <= 5)),
  review_count     integer check (review_count is null or review_count >= 0),
  link             text,
  source           text,
  sort_order       integer not null default 0,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  updated_by       uuid references public.travellers(id) on delete set null
);
comment on table public.accommodations is 'Shortlisted accommodation options for one stop. `source` is set to ''airbnb'' when added via the "Add from Airbnb" URL flow, otherwise null.';

-- Now that accommodations exists, attach the foreign key for a stop's
-- selected stay. ON DELETE SET NULL: removing the selected accommodation
-- option simply clears the selection, it never deletes the stop.
alter table public.stops
  drop constraint if exists stops_selected_accommodation_id_fkey;
alter table public.stops
  add constraint stops_selected_accommodation_id_fkey
  foreign key (selected_accommodation_id)
  references public.accommodations(id)
  on delete set null;

-- --- journey_items (transport legs + stopovers) -----------------------------
-- Legs and stopovers share one ordered list per stop in the app (Journey.js),
-- so they share one table + one sort_order sequence here too, distinguished
-- by item_type. Leg-only and stopover-only columns are simply left null on
-- rows of the other type.
create table if not exists public.journey_items (
  id               uuid primary key default gen_random_uuid(),
  stop_id          uuid not null references public.stops(id) on delete cascade,
  item_type        text not null check (item_type in ('leg', 'stopover')),
  sort_order       integer not null default 0,

  -- leg-only fields
  mode             text,           -- 'train' | 'flight' | 'bus' | 'car' | 'ferry' | 'other' | ''
  dur              text,           -- free-text duration/description (also used by stopovers)
  cost             numeric(10,2) not null default 0 check (cost >= 0),
  dep_date         date,
  dep_time         time,
  dep_loc          text,
  arr_date         date,
  arr_time         time,
  arr_loc          text,
  booking_ref      text,
  service_number   text,
  traveller_ids    uuid[] not null default '{}',  -- travellers assigned to this leg

  -- stopover-only field
  loc              text,           -- stopover location name

  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  updated_by       uuid references public.travellers(id) on delete set null
);
comment on table public.journey_items is 'The ordered transport into one stop: an interleaved sequence of legs and stopovers, same shape as Journey.js''s in-app model. dur is a free-text description on both leg and stopover rows.';

-- --- activities --------------------------------------------------------
create table if not exists public.activities (
  id           uuid primary key default gen_random_uuid(),
  stop_id      uuid not null references public.stops(id) on delete cascade,
  name         text not null default '',
  link         text,
  cost         numeric(10,2) not null default 0 check (cost >= 0),
  image_url    text,
  travel_time  text,
  sort_order   integer not null default 0,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  updated_by   uuid references public.travellers(id) on delete set null
);
comment on table public.activities is 'Things-to-do options for one stop.';

-- --- activity_votes --------------------------------------------------------
-- A normalized row per traveller/activity — presence of a row IS the vote
-- (binary selected/not-selected, matching the app's voting model exactly).
-- This is deliberately NOT a shared jsonb column on `activities`: two people
-- voting on the same activity at the same moment would otherwise read the
-- same old row and one could silently overwrite the other's vote. Separate
-- rows mean their votes are two independent inserts — no clobbering.
create table if not exists public.activity_votes (
  activity_id   uuid not null references public.activities(id) on delete cascade,
  traveller_id  uuid not null references public.travellers(id) on delete cascade,
  created_at    timestamptz not null default now(),
  primary key (activity_id, traveller_id)
);
comment on table public.activity_votes is 'One row = one traveller''s vote for one activity. Vote = row exists. Un-vote = row deleted.';

-- --- accommodation_votes -----------------------------------------------
create table if not exists public.accommodation_votes (
  accommodation_id  uuid not null references public.accommodations(id) on delete cascade,
  traveller_id      uuid not null references public.travellers(id) on delete cascade,
  created_at        timestamptz not null default now(),
  primary key (accommodation_id, traveller_id)
);
comment on table public.accommodation_votes is 'One row = one traveller''s vote for one accommodation option. Same insert/delete pattern as activity_votes, for the same concurrency-safety reason.';

-- --- extra_costs ---------------------------------------------------------
create table if not exists public.extra_costs (
  id           uuid primary key default gen_random_uuid(),
  trip_id      uuid not null references public.trips(id) on delete cascade,
  label        text not null default '',
  amount       numeric(10,2) not null default 0 check (amount >= 0),
  sort_order   integer not null default 0,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);
comment on table public.extra_costs is 'Trip-level costs that aren''t tied to one destination, e.g. international flights, visas/insurance.';


-- ----------------------------------------------------------------------------
-- 2. Indexes
-- ----------------------------------------------------------------------------
-- sort_order is a plain rewritable integer, not a unique/gapless sequence —
-- at this trip's scale (a handful of stops/activities/accommodation options
-- per list) a full reindex on reorder is cheap, so no fractional-index or
-- uniqueness machinery is needed here.

create index if not exists idx_trip_access_user on public.trip_access(user_id);
create index if not exists idx_travellers_trip on public.travellers(trip_id);
create index if not exists idx_stops_trip_sort on public.stops(trip_id, sort_order);
create index if not exists idx_stops_selected_accommodation on public.stops(selected_accommodation_id);
create index if not exists idx_accommodations_stop_sort on public.accommodations(stop_id, sort_order);
create index if not exists idx_journey_items_stop_sort on public.journey_items(stop_id, sort_order);
create index if not exists idx_activities_stop_sort on public.activities(stop_id, sort_order);
create index if not exists idx_activity_votes_traveller on public.activity_votes(traveller_id);
create index if not exists idx_accommodation_votes_traveller on public.accommodation_votes(traveller_id);
create index if not exists idx_extra_costs_trip_sort on public.extra_costs(trip_id, sort_order);


-- ----------------------------------------------------------------------------
-- 3. Trip membership — invite code + access check
-- ----------------------------------------------------------------------------
-- WHY THIS EXISTS: the app will sign every visitor in via Supabase anonymous
-- auth automatically. Once signed in, that visitor's session has Postgres
-- role `authenticated` — the SAME role a genuine family member's session
-- has. A policy that simply says "anyone authenticated may read/write" is
-- therefore equivalent to "anyone who finds the public GitHub Pages URL and
-- loads the page" — since the app itself silently grants every visitor an
-- authenticated session with no gate in between. `authenticated` alone is
-- NOT a meaningful boundary for a public static site; it only proves "this
-- is a real browser session", not "this person is family".
--
-- THE FIX: a single shared trip invite code (a passphrase, not a password —
-- no email/account). A visitor enters it once; the app calls join_trip()
-- below, which checks the code and — only on success — inserts a row into
-- trip_access for their session's user id. From then on their session is a
-- genuine trip member, and every table's RLS policy (section 4) checks
-- trip_access, not just "authenticated". The code is entered once per
-- browser (Supabase's own SDK already persists the session in localStorage,
-- same as any Supabase app) — no repeated friction for family members who
-- don't clear their browser data.

-- Small stable helper so every table's RLS policy can say
-- `is_trip_member(trip_id)` instead of repeating this subquery everywhere.
-- SECURITY DEFINER + a locked-down search_path is the standard, documented
-- Supabase pattern for auth-check helpers called from inside RLS policies.
create or replace function public.is_trip_member(p_trip_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.trip_access
    where trip_id = p_trip_id and user_id = auth.uid()
  );
$$;

revoke execute on function public.is_trip_member(uuid) from public;
grant execute on function public.is_trip_member(uuid) to authenticated;

-- The only way a row can ever appear in trip_access. Runs with the
-- function owner's privileges (SECURITY DEFINER), which is how it's allowed
-- to read the otherwise-inaccessible trip_invite_codes table and insert
-- into trip_access even though ordinary sessions have no direct grant to do
-- either — the invite-code check happens here, once, server-side, not in
-- the browser.
create or replace function public.join_trip(trip_code text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_trip_id uuid;
begin
  if auth.uid() is null then
    raise exception 'Not authenticated';
  end if;

  select trip_id into v_trip_id
  from public.trip_invite_codes
  where code_hash = crypt(trip_code, code_hash)
  limit 1;

  if v_trip_id is null then
    raise exception 'Invalid trip code';
  end if;

  insert into public.trip_access (trip_id, user_id)
  values (v_trip_id, auth.uid())
  on conflict (trip_id, user_id) do nothing;
end;
$$;

revoke execute on function public.join_trip(text) from public;
grant execute on function public.join_trip(text) to authenticated;

-- Example of setting the actual code once a trip row exists (the later
-- migration step creates that row) — NOT run here, just documented:
--   insert into public.trip_invite_codes (trip_id, code_hash)
--   values ('<the trip''s id>', crypt('choose-a-memorable-family-phrase', gen_salt('bf')));


-- ----------------------------------------------------------------------------
-- 4. updated_at trigger
-- ----------------------------------------------------------------------------
-- One shared trigger function, applied to every table that has an
-- updated_at column, so "when was this last touched" is always accurate
-- and set by the database itself — never something the app has to remember
-- to set on every write.

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_updated_at on public.trips;
create trigger set_updated_at
  before update on public.trips
  for each row execute function public.set_updated_at();

drop trigger if exists set_updated_at on public.travellers;
create trigger set_updated_at
  before update on public.travellers
  for each row execute function public.set_updated_at();

drop trigger if exists set_updated_at on public.stops;
create trigger set_updated_at
  before update on public.stops
  for each row execute function public.set_updated_at();

drop trigger if exists set_updated_at on public.accommodations;
create trigger set_updated_at
  before update on public.accommodations
  for each row execute function public.set_updated_at();

drop trigger if exists set_updated_at on public.journey_items;
create trigger set_updated_at
  before update on public.journey_items
  for each row execute function public.set_updated_at();

drop trigger if exists set_updated_at on public.activities;
create trigger set_updated_at
  before update on public.activities
  for each row execute function public.set_updated_at();

drop trigger if exists set_updated_at on public.extra_costs;
create trigger set_updated_at
  before update on public.extra_costs
  for each row execute function public.set_updated_at();

-- activity_votes / accommodation_votes have no updated_at: a vote is only
-- ever inserted or deleted, never edited in place, so there's nothing to
-- timestamp beyond created_at.


-- ----------------------------------------------------------------------------
-- 5. Row Level Security
-- ----------------------------------------------------------------------------
-- Model: this is one shared, private trip for a small trusted group. The
-- real boundary is trip MEMBERSHIP (trip_access, section 3) — not merely
-- "authenticated". Every application table's policy checks
-- is_trip_member(trip_id) (or, for tables one join away from a trip_id,
-- the equivalent EXISTS check up to their owning stop). An anonymous-auth
-- session that has never called join_trip() successfully has no row in
-- trip_access, so is_trip_member() returns false and every one of these
-- policies denies it — being "authenticated" is necessary but no longer
-- sufficient.
--
-- If finer-grained access (e.g. "only this traveller can edit their own
-- vote") is ever wanted, that's a later, additive policy change — not
-- needed for this trip.

-- trip_invite_codes: RLS enabled, NO policies for authenticated/anon at
-- all. That is deliberate, not an oversight — it means this table cannot be
-- read, inserted, updated or deleted via the API by anyone, ever; only
-- join_trip() (SECURITY DEFINER) can see it.
alter table public.trip_invite_codes enable row level security;

-- trip_access: a member may see their OWN membership rows (so the app can
-- ask "have I already joined this trip?"). No insert/update/delete policy
-- for ordinary roles — membership is only ever granted by join_trip().
alter table public.trip_access enable row level security;
drop policy if exists "read own membership" on public.trip_access;
create policy "read own membership" on public.trip_access
  for select to authenticated
  using (user_id = auth.uid());

alter table public.trips enable row level security;
drop policy if exists "authenticated full access" on public.trips;
drop policy if exists "trip members full access" on public.trips;
create policy "trip members full access" on public.trips
  for all to authenticated
  using (public.is_trip_member(id))
  with check (public.is_trip_member(id));

alter table public.travellers enable row level security;
drop policy if exists "authenticated full access" on public.travellers;
drop policy if exists "trip members full access" on public.travellers;
create policy "trip members full access" on public.travellers
  for all to authenticated
  using (public.is_trip_member(trip_id))
  with check (public.is_trip_member(trip_id));

alter table public.stops enable row level security;
drop policy if exists "authenticated full access" on public.stops;
drop policy if exists "trip members full access" on public.stops;
create policy "trip members full access" on public.stops
  for all to authenticated
  using (public.is_trip_member(trip_id))
  with check (public.is_trip_member(trip_id));

-- accommodations/journey_items/activities are one join away from trip_id
-- (via their owning stop) rather than having their own trip_id column —
-- kept that way deliberately, to avoid denormalizing trip_id onto every
-- table just to simplify these policies. The EXISTS below is the small,
-- direct cost of that choice.
alter table public.accommodations enable row level security;
drop policy if exists "authenticated full access" on public.accommodations;
drop policy if exists "trip members full access" on public.accommodations;
create policy "trip members full access" on public.accommodations
  for all to authenticated
  using (exists (
    select 1 from public.stops s
    where s.id = accommodations.stop_id and public.is_trip_member(s.trip_id)
  ))
  with check (exists (
    select 1 from public.stops s
    where s.id = accommodations.stop_id and public.is_trip_member(s.trip_id)
  ));

alter table public.journey_items enable row level security;
drop policy if exists "authenticated full access" on public.journey_items;
drop policy if exists "trip members full access" on public.journey_items;
create policy "trip members full access" on public.journey_items
  for all to authenticated
  using (exists (
    select 1 from public.stops s
    where s.id = journey_items.stop_id and public.is_trip_member(s.trip_id)
  ))
  with check (exists (
    select 1 from public.stops s
    where s.id = journey_items.stop_id and public.is_trip_member(s.trip_id)
  ));

alter table public.activities enable row level security;
drop policy if exists "authenticated full access" on public.activities;
drop policy if exists "trip members full access" on public.activities;
create policy "trip members full access" on public.activities
  for all to authenticated
  using (exists (
    select 1 from public.stops s
    where s.id = activities.stop_id and public.is_trip_member(s.trip_id)
  ))
  with check (exists (
    select 1 from public.stops s
    where s.id = activities.stop_id and public.is_trip_member(s.trip_id)
  ));

-- The vote tables are two joins away from trip_id (activity/accommodation
-- -> stop -> trip).
alter table public.activity_votes enable row level security;
drop policy if exists "authenticated full access" on public.activity_votes;
drop policy if exists "trip members full access" on public.activity_votes;
create policy "trip members full access" on public.activity_votes
  for all to authenticated
  using (exists (
    select 1 from public.activities a
    join public.stops s on s.id = a.stop_id
    where a.id = activity_votes.activity_id and public.is_trip_member(s.trip_id)
  ))
  with check (exists (
    select 1 from public.activities a
    join public.stops s on s.id = a.stop_id
    where a.id = activity_votes.activity_id and public.is_trip_member(s.trip_id)
  ));

alter table public.accommodation_votes enable row level security;
drop policy if exists "authenticated full access" on public.accommodation_votes;
drop policy if exists "trip members full access" on public.accommodation_votes;
create policy "trip members full access" on public.accommodation_votes
  for all to authenticated
  using (exists (
    select 1 from public.accommodations ac
    join public.stops s on s.id = ac.stop_id
    where ac.id = accommodation_votes.accommodation_id and public.is_trip_member(s.trip_id)
  ))
  with check (exists (
    select 1 from public.accommodations ac
    join public.stops s on s.id = ac.stop_id
    where ac.id = accommodation_votes.accommodation_id and public.is_trip_member(s.trip_id)
  ));

alter table public.extra_costs enable row level security;
drop policy if exists "authenticated full access" on public.extra_costs;
drop policy if exists "trip members full access" on public.extra_costs;
create policy "trip members full access" on public.extra_costs
  for all to authenticated
  using (public.is_trip_member(trip_id))
  with check (public.is_trip_member(trip_id));


-- ----------------------------------------------------------------------------
-- 6. Storage — trip photos bucket
-- ----------------------------------------------------------------------------
-- Destination photos, activity images, accommodation images and the hero
-- photo all go in one bucket as files; the tables above only ever store the
-- resulting URL/path (photo_url / image_url / hero_photo_url), never image
-- bytes/base64.
--
-- PRIVATE bucket (public = false), gated by the same trip membership as
-- every table above — not merely "authenticated". Earlier drafts of this
-- file made the bucket publicly readable for simplicity; on review, that
-- doesn't fit "private family trip" once anonymous auth means literally
-- any site visitor can become "authenticated", so it's replaced with the
-- same is_trip_member() check used everywhere else.
--
-- HOW THIS WORKS: every uploaded file's path must start with its trip's id
-- as the first folder segment, e.g. `<trip_id>/stops/<stop_id>/photo.jpg`.
-- storage.foldername(name) splits that path into segments; the policies
-- below check that segment [1] is a trip the caller is a member of. This is
-- a real, load-bearing consequence for whoever wires up uploads later: the
-- upload code must put files under that `<trip_id>/...` prefix, and because
-- the bucket is private, the frontend must fetch images via an authenticated
-- request (e.g. supabase.storage.from('trip-photos').download(...) or a
-- signed URL) rather than a plain public CDN <img src> URL.

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'trip-photos',
  'trip-photos',
  false,
  10485760, -- 10 MB per file
  array['image/jpeg', 'image/png', 'image/webp', 'image/gif']
)
on conflict (id) do update
  set public = excluded.public,
      file_size_limit = excluded.file_size_limit,
      allowed_mime_types = excluded.allowed_mime_types;

-- NOTE ON OWNERSHIP: storage.objects is a Supabase-MANAGED table, owned by
-- an internal Supabase role (not by the `postgres`/project-owner role this
-- script runs as). Row Level Security is already permanently enabled on it
-- by Supabase — you cannot toggle it yourself, and trying to
-- (`alter table storage.objects enable row level security;`) fails with
-- `ERROR: 42501: must be owner of table objects`, because ALTER TABLE
-- requires true table ownership regardless of what state RLS is already
-- in. That line used to be here and has been removed — it was never
-- needed, only harmful. CREATE POLICY / DROP POLICY on storage.objects are
-- unaffected by this and are the actual, Supabase-supported way to manage
-- its access rules; only structural ALTER TABLE on storage.objects itself
-- is off-limits to a project owner.

drop policy if exists "Public read access for trip photos" on storage.objects;
drop policy if exists "Trip members can read trip photos" on storage.objects;
create policy "Trip members can read trip photos"
  on storage.objects for select
  to authenticated
  using (
    bucket_id = 'trip-photos'
    and public.is_trip_member((storage.foldername(name))[1]::uuid)
  );

drop policy if exists "Authenticated upload trip photos" on storage.objects;
drop policy if exists "Trip members can upload trip photos" on storage.objects;
create policy "Trip members can upload trip photos"
  on storage.objects for insert
  to authenticated
  with check (
    bucket_id = 'trip-photos'
    and public.is_trip_member((storage.foldername(name))[1]::uuid)
  );

drop policy if exists "Authenticated update trip photos" on storage.objects;
drop policy if exists "Trip members can update trip photos" on storage.objects;
create policy "Trip members can update trip photos"
  on storage.objects for update
  to authenticated
  using (
    bucket_id = 'trip-photos'
    and public.is_trip_member((storage.foldername(name))[1]::uuid)
  )
  with check (
    bucket_id = 'trip-photos'
    and public.is_trip_member((storage.foldername(name))[1]::uuid)
  );

drop policy if exists "Authenticated delete trip photos" on storage.objects;
drop policy if exists "Trip members can delete trip photos" on storage.objects;
create policy "Trip members can delete trip photos"
  on storage.objects for delete
  to authenticated
  using (
    bucket_id = 'trip-photos'
    and public.is_trip_member((storage.foldername(name))[1]::uuid)
  );


-- ----------------------------------------------------------------------------
-- 7. Realtime
-- ----------------------------------------------------------------------------
-- trip_access / trip_invite_codes are deliberately NOT added here: they
-- change rarely, the app has no need to watch them live, and
-- trip_invite_codes should never be surfaced to a Realtime subscription at
-- all (Realtime respects RLS, but there is simply no reason to include it).
-- Adds every application table to Supabase's built-in `supabase_realtime`
-- publication, so any of them CAN be subscribed to later for live updates
-- (e.g. "Dom votes -> Sarah sees it without refreshing"). Being in the
-- publication costs nothing on its own — nothing broadcasts until the app
-- actually opens a Realtime subscription, which it does not do yet.
--
-- This assumes the `supabase_realtime` publication already exists, which it
-- does on every standard Supabase project by default.
--
-- REPLICA IDENTITY FULL is set on each table so that a future UPDATE/DELETE
-- Realtime event carries the complete old row, not just its primary key —
-- lets the app merge a change without an extra fetch. This only affects
-- what's logged for replication; it has no effect on the app today.

do $$
declare
  t text;
begin
  foreach t in array array[
    'trips', 'travellers', 'stops', 'journey_items',
    'activities', 'activity_votes',
    'accommodations', 'accommodation_votes', 'extra_costs'
  ]
  loop
    execute format('alter table public.%I replica identity full', t);

    if not exists (
      select 1 from pg_publication_tables
      where pubname = 'supabase_realtime'
        and schemaname = 'public'
        and tablename = t
    ) then
      execute format('alter publication supabase_realtime add table public.%I', t);
    end if;
  end loop;
end $$;


-- ============================================================================
-- End of setup. Nothing below this line runs — it's a reference rollback
-- script in case this ever needs to be fully undone (see the accompanying
-- explanation, question 7). Copy the block out and run it separately;
-- it is commented out here on purpose so pasting/running this whole file
-- never triggers it.
-- ============================================================================

-- do $$
-- declare
--   t text;
-- begin
--   foreach t in array array[
--     'trips', 'travellers', 'stops', 'journey_items',
--     'activities', 'activity_votes',
--     'accommodations', 'accommodation_votes', 'extra_costs'
--   ]
--   loop
--     if exists (
--       select 1 from pg_publication_tables
--       where pubname = 'supabase_realtime'
--         and schemaname = 'public'
--         and tablename = t
--     ) then
--       execute format('alter publication supabase_realtime drop table public.%I', t);
--     end if;
--   end loop;
-- end $$;
--
-- drop policy if exists "Trip members can delete trip photos" on storage.objects;
-- drop policy if exists "Trip members can update trip photos" on storage.objects;
-- drop policy if exists "Trip members can upload trip photos" on storage.objects;
-- drop policy if exists "Trip members can read trip photos" on storage.objects;
-- delete from storage.objects where bucket_id = 'trip-photos';
-- delete from storage.buckets where id = 'trip-photos';
--
-- drop table if exists public.extra_costs;
-- drop table if exists public.accommodation_votes;
-- drop table if exists public.activity_votes;
-- drop table if exists public.activities;
-- drop table if exists public.journey_items;
-- drop table if exists public.accommodations;
-- drop table if exists public.stops;
-- drop table if exists public.travellers;
-- drop table if exists public.trip_access;
-- drop table if exists public.trip_invite_codes;
-- drop table if exists public.trips;
--
-- drop function if exists public.join_trip(text);
-- drop function if exists public.is_trip_member(uuid);
-- drop function if exists public.set_updated_at();
